[tool.black]
line-length = 88
target-version = ["py312", "py313"]

[tool.ruff]
line-length = 88
target-version = "py312"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    # https://beta.ruff.rs/docs/rules/missing-type-self/
    # "ANN101", # the rule has been removed
    # https://beta.ruff.rs/docs/rules/#pydocstyle-d
    "D100",
    "D101",
    "D102",
    "D103",
    "D104",
    "D105",
    "D106",
    "D107",
    # https://beta.ruff.rs/docs/rules/commented-out-code/
    "ERA001",
    # https://beta.ruff.rs/docs/rules/missing-trailing-comma/
    "COM812",
    # https://beta.ruff.rs/docs/rules/pytest-unittest-assertion/
    "PT009",
    # https://docs.astral.sh/ruff/rules/single-line-implicit-string-concatenation/
    # the rule may cause conflicts when used with the formatter
    "ISC001"
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.mypy]
python_version = "3.12"

[[tool.mypy.overrides]]
module = [
    "openrazer",
    "openrazer.client",
    "openrazer.client.devices",
    "openrazer.client.devices.mice"
]
ignore_missing_imports = true
